import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import Switch from "@mui/material/Switch";
import Button from "@mui/material/Button";
import Stack from "@mui/material/Stack";
import TextField from "@mui/material/TextField";

export default function Home() {
  const [people, setPeople] = useState([]);
  const [loading, setLoading] = useState(true);
  const [randomPerson, setRandomPerson] = useState(undefined);

  const fetchPeople = async () => {
    const response = await fetch("/api/people");
    const data = await response.json();
    setLoading(false);
    setPeople(data);
  };

  const setPersonChecked = (index) => {
    const newPeople = [...people];
    newPeople[index].available = !newPeople[index].available;
    setPeople(newPeople);
  };

  const getRandomPerson = () => {
    const availables = people.filter((p) => p.available);
    if (!availables.length) return;

    var random = availables[Math.floor(Math.random() * availables.length)];
    setPersonChecked(random.id);
    setRandomPerson(random);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {loading && (
          <Button variant="contained" onClick={fetchPeople}>
            Load People
          </Button>
        )}
        {!loading && (
          <Stack spacing={1} direction="column">
            {people.map((person) => {
              return (
                <Stack spacing={1} direction="column" key={person.id}>
                  <div>
                    {person.name}
                    <Switch
                      checked={person.available}
                      onChange={() => setPersonChecked(person.id)}
                      name={person.name}
                      color="primary"
                    />
                  </div>
                </Stack>
              );
            })}

            <Button
              style={{ marginBottom: "10px" }}
              variant="contained"
              color="secondary"
              onClick={getRandomPerson}
            >
              Get Random Person
            </Button>

            <TextField color="secondary" focused value={randomPerson?.name} />
          </Stack>
        )}
      </main>
    </div>
  );
}
